version: '3.7'
services:

  client-service:
    image: {gradleImagePath}
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      env: compose
    command: >
      "
      echo-versions &&
      gradle spring-boot:run
      "
